Images addition
WildCodeSchool/bordeaux-0218-php-festizik pull request #12
Opened 2018-04-20 09:51 UTC by MonochromePinguin

All this PR contains is the images referenced into DB. No code change.

2018-04-20 12:28 UTC, AurelienBarbier commented on src/Controller/UserController.php
>              $this->storeMsg('Cette page n\'est pas prévue pour être utilisée avec la méthode POST');
Ces stored messages sont prévus pour être affichés à l'internaute, ou c'est pour gérer du Log pour le développeur ?

2018-04-21 15:33 UTC, MonochromePinguin commented on src/Controller/UserController.php
>              $this->storeMsg('Cette page n\'est pas prévue pour être utilisée avec la méthode POST');
Whaaat ? Et bieeeen apparemment voici une *grosse* boulette de ma part – aucune modif de code n'était _censée_ survenir dans cette branche, juste un ajout officiel de fichiers. J'ai donc bourdé avec branches et/ou stash ... Je revois çà auj'. Sinon, cette classe c'est pour afficher des messages d'erreur, destinés à l'internaute, à des endroits appropriés dans la page et non lors de l'exécution du script. L'enregistrement d'un journal d'erreur dans la BdD a été reporté à une  version 𝑛 ultérieure.

2018-04-21 16:41 UTC, MonochromePinguin commented on src/Controller/UserController.php
>              $this->storeMsg('Cette page n\'est pas prévue pour être utilisée avec la méthode POST');
Les fichiers image apportés par cette branche étant ajoutés par la branche «Artist», cette PR n'est plus nécessaire !

2018-04-23 09:34 UTC, AurelienBarbier commented on src/Controller/UserController.php
>              $this->storeMsg('Cette page n\'est pas prévue pour être utilisée avec la méthode POST');
Je pense que l'internaute n'a pas besoin d'avoir ce niveau de détails dans les erreurs, parler de méthode post à un internaute ne l'interresse. Le prévenir qu'il y a eu une erreur, ok, mais pas plus.

2018-04-23 09:38 UTC, AurelienBarbier requested changes
On est pas sensé avoir de `.idea/*` dans nos push

2018-04-25 12:41 UTC, closed without merging