Admin concerts 2
WildCodeSchool/bordeaux-0218-php-festizik pull request #20
Opened 2018-05-03 15:34 UTC by MonochromePinguin

addition of a logout button and other fixes.

2018-05-03 15:52 UTC, AurelienBarbier commented on public/assets/css/adminStyle.css
> +    max-width  : 14em;
j'aime pas trop les largeurs en em

2018-05-03 15:53 UTC, AurelienBarbier requested changes

2018-05-03 15:53 UTC, AurelienBarbier commented on src/View/Admin/concerts.html.twig
> + {#          <div id="oneConcertBlock">
Oh, le joli bloc de code mort !
On ne sait jamais, ça peux toujours servir ?

2018-05-03 16:52 UTC, MonochromePinguin commented on src/View/Admin/concerts.html.twig
> + {#          <div id="oneConcertBlock">
C'est exactement ce que j'allais répondre (c'était sensé servir, mais par manque de temps j'ai arrété le dév' de cette fonctionnalité) ... Ok, d'accord, mea culpa, je vais l'enlever.

2018-05-03 16:52 UTC, MonochromePinguin commented on public/assets/css/adminStyle.css
> +    max-width  : 14em;
Beeeen ... Avec des em, la largeur de l'élément étant relative à celle du texte qu'il contient, ce dernier ne peut plus dépasser sur la droite (ou plus exactement être rogné) quand on change le niveau de zoom ou la largeur de fenêtre sous certaines combinaisons navigateur/version/réglages perso ... C'est la seule solution que j'ai trouvé pour que ça reste propre.

2018-05-04 08:21 UTC, AurelienBarbier approved these changes

2018-05-04 08:21 UTC, merged

2018-05-04 08:22 UTC, AurelienBarbier commented on public/assets/css/adminStyle.css
> +    max-width  : 14em;
ce n'était qu'un avis personnel :wink: ce n'était en rien rédhibitoire.