Programmation page ii
WildCodeSchool/bordeaux-0218-php-festizik pull request #4
Opened 2018-04-11 15:44 UTC by MonochromePinguin

This first skeleton is functional enough for a pull request (from "programmationPageII" into "dev"). The page lacks ordering and filtering buttons, a better layout (1 section per day), advanced search features, etc but It Works©.

2018-04-16 08:17 UTC, AurelienBarbier requested changes

2018-04-16 08:17 UTC, AurelienBarbier commented on app/dispatcher.php
> +use misc\ErrorStore as ErrorStore;
misc en UpperCamelCase / PascalCase

2018-04-16 08:17 UTC, AurelienBarbier commented on app/dispatcher.php
> +//TODO : the PDO connection should be given to the new $class() here !
:1st_place_medal:

2018-04-16 08:17 UTC, AurelienBarbier commented on app/dispatcher.php
> +use misc\ErrorStore as ErrorStore;
(https://en.wikipedia.org/wiki/Camel_case#History_of_modern_technical_use)

2018-04-16 08:17 UTC, AurelienBarbier commented on src/View/Admin/list.html.twig
> +          {% for e in artists %}
`e` n'est pas très explicite, un `artist` serait plus parlant

2018-04-16 08:17 UTC, AurelienBarbier commented on src/View/User/concerts.html.twig
> +    {% if errorList %}
Bien pour le error list, mais, s'il était présent dans le layout, en direct ou en include, peut être pourrait on ne gérer les errors qu'a un seul et unique endroit, peu importe la page en cours ;)

2018-04-16 08:17 UTC, AurelienBarbier commented on src/View/User/concerts.html.twig
> +          {% for c in concerts %}
idem, soit plus explicite pour tes collaborateurs, ou pour le Sebastien Roze du futur.

2018-04-16 08:17 UTC, AurelienBarbier commented on src/View/User/concerts.html.twig
> +                        {{ c.hour }}
exemple "c.hour" n'est pas des plus parlant "à froid".

2018-04-16 08:17 UTC, AurelienBarbier commented on src/View/User/testList.html.twig
> +      {% for c in concerts %}
idem

2018-04-18 09:51 UTC, MonochromePinguin commented on app/dispatcher.php
> +use misc\ErrorStore as ErrorStore;
done

2018-04-18 10:02 UTC, MonochromePinguin commented on src/View/User/concerts.html.twig
> +          {% for c in concerts %}
done

2018-04-18 10:03 UTC, MonochromePinguin commented on src/View/User/concerts.html.twig
> +                        {{ c.hour }}
done

2018-04-18 10:03 UTC, MonochromePinguin commented on src/View/User/testList.html.twig
> +      {% for c in concerts %}
done

2018-04-18 12:11 UTC, MonochromePinguin commented on src/View/User/concerts.html.twig
> +    {% if errorList %}
Done! The error list in isolated into ist own twig file everyone can include or not.

2018-04-18 13:25 UTC, AurelienBarbier approved these changes

2018-04-18 13:25 UTC, merged

2018-04-18 13:37 UTC, MonochromePinguin commented on app/dispatcher.php
> +//TODO : the PDO connection should be given to the new $class() here !
Done! With some testing needed, because it modify the core MVC